import { createElement } from '@lwc/engine-dom';
import BatchAlikeAndConcern from 'c/batchAlikeAndConcern';

describe('c-batch-alike-and-concern', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-batch-alike-and-concern', {
            is: BatchAlikeAndConcern
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});