public class AccountTriggerHandlerBank {
  /*  public static void accntRating(List<Account> accntList){
        for(Account acc: accntList){
            if(acc.Industry == 'Banking' || acc.Industry == 'Healthcare' ){
                acc.Rating = 'Hot';
            }
        }
    }*/
    /*
    public static void updateAccounts(List<Account> accountList) {
        List<Account> accountsToUpdate = new List<Account>();

        for (Account acc : accountList) {
            if (acc.Industry == 'Technology') {
                Account updatedAcc = new Account();
                updatedAcc.Id = acc.Id;
                updatedAcc.Description = 'This account belongs to the Technology industry.';
                accountsToUpdate.add(updatedAcc);
            }
        }

        if (!accountsToUpdate.isEmpty()) {
            update accountsToUpdate;
        }
    }
*/
}